#                                                 🖥🖥🖥🖥🖥🖥🖥🖥🖥🖥🖥🖥🖥🖥
#                                                   💻Mining Lasers Config💻
#                                                   🔥Coded By Mike3132🔥
#                                                  ❤Mining Lasers Config❤
#                                                 🖥🖥🖥🖥🖥🖥🖥🖥🖥🖥🖥🖥🖥🖥
About: '&6&lBy &5Mike3132  &f-> &dVersion 1.0'
ConfigVersion: '1.0'
#☠☠☠☠ WARNING: DO NOT CHANGE ANYTHING ABOVE THIS LINE IT WILL BREAK THE PLUGIN!☠☠☠☠☠

#📝📝📝📝Permissions📝📝📝📝📝
#Laser.Give - Access to give themselves lasers. The plugin will give you the correct syntax
#Laser.Reload - Access to reload the plugin
#📝📝📝📝Permissions📝📝📝📝📝

#✍✍✍✍You can Modify the following how you wish✍✍✍✍✍
#Plugin Prefix // This shows before all chat messages
Prefix: '&4&lMining &c&lLasers &7> '
#👋👋👋👋 END OF CONFIG 👋👋👋👋👋
